config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :favorites
  resources :users
  resources :feeds do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  validates :title,  presence: true
  validates :content,  presence: true
  validates :image,  presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :photo, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :feeds
  has_many :favorites, dependent: :destroy
  mount_uploader :photo, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのブログをお気に入り解除しました"
  end

  def index
    @favorites = current_user.favorites
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action:logged_in?, only:[:new,:create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end
  
  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if params[:back]
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      else
        if @feed.save
          FeedMailer.feed_mail(@feed).deliver
          format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
          format.json { render :show, status: :created, location: @feed }
        else
          format.html { render :new }
          format.json { render json: @feed.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :title, :content, :user_id, :feed_id, :email)
  end

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def correct_user
    if current_user.id != @feed.user_id
      flash[:notice] = "権限がないです"
      redirect_to feeds_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action:logged_in?, only:[:new,:create]
  before_action :own_user, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
      else
        render :new
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to show, notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :password,:password_confirmation,:photo, :photo_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def own_user
    if current_user.id != @user.id
      redirect_to user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り</h1>

<table>
  <thead>
    <tr>
      <th>user</th>
      <th>title</th>
      <th>content</th>
      <th>image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.feed.user.name %></td>
        <td><%= favorite.feed.title %></td>
        <td><%= favorite.feed.content %></td>
        <td><%= image_tag favorite.feed.image.url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= form.hidden_field :user %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>name:<%= @feed.user.name %></p>
  <p>title:<%= @feed.title %></p>
  <p>content:<%= @feed.content %></p>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.submit "投稿する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %>
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>user</th>
      <th>title</th>
      <th>content</th>
      <th>image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.user.name %></td>
        <td><%= feed.title %></td>
        <td><%= feed.content %></td>
        <td><%= image_tag feed.image.url %></td>
        <td><%= link_to '詳細', feed %></td>

        <% if current_user.id == feed.user.id %>
          <td><%= link_to '編集', edit_feed_path(feed) %></td>
          <td><%= link_to '削除', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @feed.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入り登録', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "New", new_feed_path %>
      <%= link_to "Feeds", feeds_path %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>

  <footer>
    <p>2020 DIC Kadai</p>
  </footer>
</html>

app/views/users/edit.html.erb
<h1>プロフィールの編集</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<% if logged_in? %>
  <h1><%= @user.name %>のページ</h1>
  <p>メールアドレス: <%= @user.email %></p>

  <p id="notice"><%= notice %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag @user.photo.url %>
  </p>

  <% if current_user.id == @user.id %>
    <%= link_to 'お気に入り一覧', favorites_path %> |
    <%= link_to 'プロフィールを編集', edit_user_path(@user) %>
  <% end %>

<% else %>
  <h1>ユーザー：<%= @user.name %>を登録しました。</h1>
  <h3><%= link_to "ログイン", new_session_path %>してください</h3>
<% end %>